const products = [
  { id: 1, name: "Telefon", price: 1200, category: "Elektronika", stock: 15, brand: "Samsung" },
  { id: 2, name: "Noutbuk", price: 2500, category: "Elektronika", stock: 8, brand: "Apple" },
  { id: 3, name: "Qulaqlıq", price: 150, category: "Aksesuar", stock: 30, brand: "Sony" },
  { id: 4, name: "Monitor", price: 600, category: "Elektronika", stock: 12, brand: "LG" },
  { id: 5, name: "Printer", price: 400, category: "Ofis", stock: 5, brand: "HP" },
  { id: 6, name: "Maus", price: 50, category: "Aksesuar", stock: 40, brand: "Logitech" },
  { id: 7, name: "Klaviatura", price: 80, category: "Aksesuar", stock: 25, brand: "Logitech" },
  { id: 8, name: "Planşet", price: 900, category: "Elektronika", stock: 10, brand: "Huawei" },
  { id: 9, name: "Kamera", price: 1800, category: "Foto/Video", stock: 6, brand: "Canon" },
  { id: 10, name: "Smart saat", price: 350, category: "Elektronika", stock: 20, brand: "Xiaomi" },
  { id: 11, name: "Televizor", price: 2200, category: "Elektronika", stock: 7, brand: "Samsung" },
  { id: 12, name: "Kondisioner", price: 1500, category: "Məişət", stock: 4, brand: "Bosch" },
  { id: 13, name: "Soyuducu", price: 1800, category: "Məişət", stock: 6, brand: "LG" },
  { id: 14, name: "Paltaryuyan", price: 1300, category: "Məişət", stock: 9, brand: "Bosch" },
  { id: 15, name: "Mətbəx kombaynı", price: 500, category: "Məişət", stock: 15, brand: "Philips" },
  { id: 16, name: "Kofe maşını", price: 300, category: "Məişət", stock: 20, brand: "Delonghi" },
  { id: 17, name: "Elektrik sobası", price: 700, category: "Məişət", stock: 8, brand: "Siemens" },
  { id: 18, name: "Fotoaparat obyektiv", price: 1200, category: "Foto/Video", stock: 5, brand: "Nikon" },
  { id: 19, name: "Gaming kreslosu", price: 450, category: "Ofis", stock: 12, brand: "DXRacer" },
  { id: 20, name: "Proyektor", price: 1600, category: "Ofis", stock: 3, brand: "Epson" },
  { id: 21, name: "Elektrik scooter", price: 1100, category: "Elektronika", stock: 10, brand: "Xiaomi" },
  { id: 22, name: "Dron", price: 2000, category: "Foto/Video", stock: 4, brand: "DJI" },
  { id: 23, name: "PlayStation 5", price: 1500, category: "Elektronika", stock: 6, brand: "Sony" },
  { id: 24, name: "Xbox Series X", price: 1400, category: "Elektronika", stock: 5, brand: "Microsoft" },
  { id: 25, name: "Mətbəx blenderi", price: 250, category: "Məişət", stock: 18, brand: "Philips" },
  { id: 26, name: "Tozsoran", price: 600, category: "Məişət", stock: 14, brand: "Dyson" },
  { id: 27, name: "Mikrofon", price: 200, category: "Aksesuar", stock: 22, brand: "Blue" },
  { id: 28, name: "Web kamera", price: 120, category: "Aksesuar", stock: 30, brand: "Logitech" },
  { id: 29, name: "Router", price: 180, category: "Elektronika", stock: 25, brand: "TP-Link" },
  { id: 30, name: "SSD Disk", price: 300, category: "Elektronika", stock: 40, brand: "Samsung" },
  { id: 31, name: "Hard Disk", price: 200, category: "Elektronika", stock: 35, brand: "Seagate" },
  { id: 32, name: "Powerbank", price: 100, category: "Aksesuar", stock: 50, brand: "Anker" },
  { id: 33, name: "E-book oxuyucu", price: 400, category: "Elektronika", stock: 12, brand: "Amazon Kindle" },
  { id: 34, name: "Smart lampa", price: 80, category: "Elektronika", stock: 60, brand: "Philips Hue" },
  { id: 35, name: "Smart kilid", price: 250, category: "Elektronika", stock: 15, brand: "Yale" },
  { id: 36, name: "Smart termostat", price: 300, category: "Məişət", stock: 10, brand: "Nest" },
  { id: 37, name: "Qəhvə üyüdən", price: 150, category: "Məişət", stock: 20, brand: "Delonghi" },
  { id: 38, name: "Elektrik diş fırçası", price: 120, category: "Məişət", stock: 25, brand: "Oral-B" },
  { id: 39, name: "Masaj aparatı", price: 350, category: "Məişət", stock: 8, brand: "Beurer" },
  { id: 40, name: "Smart gözlük", price: 900, category: "Elektronika", stock: 5, brand: "Meta" }
];

module.exports = products;
